# Generated by Django 5.2.9 on 2026-01-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='assets/images/default_student_photo.png', help_text='Upload a student photo', null=True, upload_to='student_photos/'),
        ),
    ]
